version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./cmd/Dockerfile
    ports:
      - "8001:8001/udp"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:alpine
    ports:
      - "6380:6379"
